package com.gmacster.leetcode.problem3;

import java.util.HashSet;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.lengthOfLongestSubstring("abcabcbb"));
        System.out.println(app.lengthOfLongestSubstring("bbbb"));
        System.out.println(app.lengthOfLongestSubstring("pwwkew"));
    }

    public int lengthOfLongestSubstring(String s) {
        
        Set<Character> set = new HashSet<>();

        int longest = 0;

        int left = 0;
        int right = 0;

        while (left < s.length() && right < s.length()) {
            if (set.contains(s.charAt(right))) {
                set.remove(s.charAt(left));
                left++;
            } else {
                set.add(s.charAt(right));
                right++;
                longest = Math.max(longest, right - left);
            }
        }

        return longest;
    }
}
